import Converter from './converter.js';
import Units from './units.js';

import accelerationDef from './definitions/acceleration.js';
import angleDef from './definitions/angle.js';
import areaDef from './definitions/area.js';
import binaryDef from './definitions/binary.js';
import densityDef from './definitions/density.js';
import distanceDef from './definitions/distance.js';
import electricCapacitanceDef from './definitions/electric.capacitance.js';
import electricCurrentDef from './definitions/electric.current.js';
import energyDef from './definitions/energy.js';
import flowRateMoleDef from './definitions/flow.rate.mole.js';
import flowRateVolumeDef from './definitions/flow.rate.volume.js';
import forceDef from './definitions/force.js';
import frequencyDef from './definitions/frequency.js';
import illuminanceDef from './definitions/illuminance.js';
import luminanceDef from './definitions/luminance.js';
import massDef from './definitions/mass.js';
import powerDef from './definitions/power.js';
import pressureDef from './definitions/pressure.js';
import temperatureDef from './definitions/temperature.js';
import timeDef from './definitions/time.js';
import torqueDef from './definitions/torque.js';
import velocityDef from './definitions/velocity.js';
import viscosityDynamicDef from './definitions/viscosity.dynamic.js';
import viscosityDynamicOilWaterDef from './definitions/viscosity.dynamic.oil-water.js';
import viscosityKinematicDef from './definitions/viscosity.kinematic.js';
import volumeDef from './definitions/volume.js';


// register all known unit types
Units.register(accelerationDef);
Units.register(angleDef);
Units.register(areaDef);
Units.register(binaryDef);
Units.register(densityDef);
Units.register(distanceDef);
Units.register(electricCapacitanceDef);
Units.register(electricCurrentDef);
Units.register(energyDef);
Units.register(flowRateMoleDef);
Units.register(flowRateVolumeDef);
Units.register(forceDef);
Units.register(frequencyDef);
Units.register(illuminanceDef);
Units.register(luminanceDef);
Units.register(massDef);
Units.register(powerDef);
Units.register(pressureDef);
Units.register(temperatureDef);
Units.register(timeDef);
Units.register(torqueDef);
Units.register(velocityDef);
Units.register(viscosityDynamicDef);
Units.register(viscosityDynamicOilWaterDef);
Units.register(viscosityKinematicDef);
Units.register(volumeDef);

export default Converter;
export { Converter, Units };
